services:
  app:
    build: .
    restart: always
    ports:
      - "8084:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://user:password@db:5432/raion-battlepass?sslmode=disable
    depends_on:
      - db
      - vp
    networks:
      - raion-battlepass-network
    command: >
      sh -c "./raion-battlepass"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./cmd:/app/cmd

  vp:
    build:
      context: ./vitepress
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    networks:
      - raion-battlepass-network
    volumes:
      - ./vitepress:/app
      - /app/node_modules

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raion-battlepass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - raion-battlepass-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d raion-battlepass"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  raion-battlepass-network:
    driver: bridge

volumes:
  db_data:
